
GET http://localhost:3000/users/21

###
GET http://localhost:3000/users

###

POST http://localhost:3000/users
content-type: application/json

{
    "user": {
        "id": "27",
        "name":"roberto",
        "age":"28",
        "email":"roberto5896@gmail.com"
    }
}

###
POST http://localhost:3000/users
content-type: application/json

{
  
}

###

PUT http://localhost:3000/users/27
content-type: application/json

{
    "user": {
        "id": "1",
        "name":"juancito",
        "age":"89",
        "email":"jh2340@gmail.com"
    }
}

### 

DELETE  http://localhost:3000/user/27
content-type: application/json


